os: linux
language: generic
dist: focal

vm:
  create:
    name: 500K-default-2006-i1

script:
  - echo "Creating custom file"
  - sudo mkdir /my-custom-dir
  - echo "Test custom image!" | sudo tee /my-custom-dir/my_custom_file.txt
  - sudo cat /my-custom-dir/my_custom_file.txt
